services:

  db:
    image: mysql:8.3
    container_name: smart-plant-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mary098
      MYSQL_DATABASE: smart_plant_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pmary098"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    container_name: smart-plant-backend
    ports:
      - "8000:8000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mary098
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: smart_plant_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: smart-plant-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
